"""Prepares a Basis project for building the avatar.

    uv run --project tools alicechan-basis-setup [--work basis/.work]

Clones BasisVR/Basis at the commit in basis/pins.json, unpacks Watari into its Packages folder,
and adds UniVRM, the avatar package and the build package to its manifest.
"""

from __future__ import annotations

import argparse
import io
import json
import shutil
import urllib.request
import zipfile
from pathlib import Path

from .common import PACKAGE_ID, fail, package_dir, repo_root, run

BUILD_PACKAGE_ID = "com.yuna0x0.alice-chan.basis-build"


def load_pins() -> dict:
    with (repo_root() / "basis" / "pins.json").open(encoding="utf-8") as handle:
        return json.load(handle)


def clone_basis(pins: dict, work: Path) -> Path:
    clone = work / "Basis"
    commit = pins["basis"]["commit"]
    if (clone / ".git").is_dir():
        head = (clone / ".git" / "HEAD").read_text(encoding="utf-8").strip()
        if head == commit:
            print(f"Basis already at {commit}")
            return clone
        run(["git", "fetch", "--depth", "1", "origin", commit], cwd=clone)
    else:
        clone.mkdir(parents=True, exist_ok=True)
        run(["git", "init", "-q"], cwd=clone)
        run(["git", "remote", "add", "origin", pins["basis"]["repository"]], cwd=clone)
        run(["git", "fetch", "--depth", "1", "origin", commit], cwd=clone)
    run(["git", "checkout", "-q", "--detach", commit], cwd=clone)
    return clone


def unpack_watari(pins: dict, packages: Path) -> None:
    watari = pins["watari"]
    target = packages / watari["package"]
    manifest = target / "package.json"
    if manifest.is_file():
        with manifest.open(encoding="utf-8") as handle:
            if json.load(handle).get("version") == watari["version"]:
                print(f"Watari {watari['version']} already present")
                return
    url = watari["zip"].format(version=watari["version"])
    print("+ download", url)
    with urllib.request.urlopen(url) as response:
        data = response.read()
    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)
    with zipfile.ZipFile(io.BytesIO(data)) as archive:
        archive.extractall(target)
    if not manifest.is_file():
        fail(f"{url} did not contain package.json at its root")


def patch_manifest(pins: dict, packages: Path) -> None:
    path = packages / "manifest.json"
    with path.open(encoding="utf-8") as handle:
        manifest = json.load(handle)
    deps = manifest["dependencies"]
    version = pins["univrm"]["version"]
    for name, url in pins["univrm"]["packages"].items():
        deps[name] = url.format(version=version)
    # Absolute file: paths, because the manifest lives in an ignored work folder and is
    # regenerated by this command; nothing else has to stay relative to it.
    deps[PACKAGE_ID] = "file:" + package_dir().as_posix()
    build_package = repo_root() / "basis" / "Packages" / BUILD_PACKAGE_ID
    deps[BUILD_PACKAGE_ID] = "file:" + build_package.as_posix()
    with path.open("w", encoding="utf-8") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")
    print(f"patched {path}")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.strip().splitlines()[0])
    parser.add_argument("--work", default="basis/.work", help="work folder, relative to the repository")
    args = parser.parse_args()

    pins = load_pins()
    work = repo_root() / args.work
    clone = clone_basis(pins, work)
    packages = clone / pins["basis"]["project"] / "Packages"
    if not (packages / "manifest.json").is_file():
        fail(f"{packages} has no manifest.json; is the project folder in pins.json right?")
    unpack_watari(pins, packages)
    patch_manifest(pins, packages)
    print(f"ok: {clone / pins['basis']['project']}")
